---
title: "EDS212_Day4_Part2"
format: html
editor: visual
---

```{r}
#| warning: false
#| echo: false

library(tidyverse)
library(palmerpenguins)
library(GGally)
library(skimr)
```

-   To install a package, you need to place the package in parentheses and in quotation marks.

-   hash \| pike

-   warning do not repeat any errors, default will show this when rendered, specific to quarto

-   echo do not repeat any code, default will show this when rendered, specific to quarto

```{r}
view(penguins)
```

## Exploratory Data Viz

Check out your data a bit:

```{r}
#| include: false

#Tell me the column names
names(penguins)

dim(penguins)
head(penguins)
tail(penguins)
```

```{r}
skim(penguins)
```

```{r}
#| warning: false
GGally::ggpairs(penguins)
```

## Jitterplot

Flipper length by species

```{r}
ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) +
    geom_jitter(width = 0.2,
                alpha = 0.5,
                aes(color = species)) +
  geom_boxplot() +
  theme_light() +
  scale_color_manual(values = c("darkorchid4", "cyan4", "goldenrod")) +
  labs(x = "Penguin species",
       y = "Flipper length (mm)",
       title = "Flipper length by penguin species")
```

```{r}
ggplot(data = penguins, aes(x= bill_length_mm)) +
  geom_histogram(aes(fill = species), color = "magenta") + 
  facet_wrap(~species, ncol = 1)
```
